# Local Development Configuration
# Uses nginx:alpine with custom config and self-signed certificates

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - web

  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - web

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    expose:
      - "3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - web

networks:
  web:
    driver: bridge 