services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - web

  nginx-proxy-acme:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_proxy_acme
    environment:
      - DEFAULT_EMAIL=jordan.bothwell@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - web
    profiles:
      - production

  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=api.amiarobot.ca
      - LETSENCRYPT_HOST=api.amiarobot.ca
      - LETSENCRYPT_EMAIL=jordan.bothwell@gmail.com
      # Python memory optimization
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - web

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=amiarobot.ca, www.amiarobot.ca
      - LETSENCRYPT_HOST=amiarobot.ca, www.amiarobot.ca
      - LETSENCRYPT_EMAIL=jordan.bothwell@gmail.com
      - VIRTUAL_PROTO=http
      # Node.js memory optimization
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=256
    volumes:
      - ./frontend:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    stdin_open: true
    tty: true
    networks:
      - web

networks:
  web:
    driver: bridge

